import { MMKV } from "react-native-mmkv";

export const storage = new MMKV();

export const allSectors = [
    { id: "observation", name: "Observação" },
    { id: "receptionC", name: "Recepção C" },
    { id: "receptionG", name: "Recepção G" },
    { id: "medicalSupport", name: "Apoio Médico" },
    { id: "fastCLM", name: "Fast CLM" },
    { id: "fastMedication", name: "Fast Medicação" },
    { id: "concierge", name: "Concierge" },
];

export const allEmployees = [
    {
        id: 1,
        name: "Henrique",
        leadership: true,
        firstReference: false,
        secondReference: false,
        sectors: {
            receptionC: false,
            receptionG: false,
            medicalSupport: false,
            observation: false,
            fastCLM: false,
            fastMedication: false,
            concierge: false,
        },
    },
    {
        id: 2,
        name: "Elisabeth",
        leadership: false,
        firstReference: false,
        secondReference: false,
        sectors: {
            receptionC: false,
            receptionG: false,
            medicalSupport: true,
            observation: false,
            fastCLM: true,
            fastMedication: false,
            concierge: true,
        },
    },
    {
        id: 3,
        name: "Geovana",
        leadership: false,
        firstReference: false,
        secondReference: false,
        sectors: {
            receptionC: true,
            receptionG: true,
            medicalSupport: false,
            observation: false,
            fastCLM: false,
            fastMedication: true,
            concierge: false,
        },
    },
    {
        id: 4,
        name: "Gustavo",
        leadership: false,
        firstReference: false,
        secondReference: false,
        sectors: {
            receptionC: true,
            receptionG: true,
            medicalSupport: false,
            observation: false,
            fastCLM: false,
            fastMedication: false,
            concierge: false,
        },
    },
    {
        id: 5,
        name: "Jessica",
        leadership: false,
        firstReference: false,
        secondReference: false,
        sectors: {
            receptionC: false,
            receptionG: false,
            medicalSupport: true,
            observation: false,
            fastCLM: true,
            fastMedication: false,
            concierge: true,
        },
    },
    {
        id: 6,
        name: "Juliana",
        leadership: false,
        firstReference: false,
        secondReference: false,
        sectors: {
            receptionC: true,
            receptionG: true,
            medicalSupport: false,
            observation: false,
            fastCLM: false,
            fastMedication: true,
            concierge: false,
        },
    },
    {
        id: 7,
        name: "Kaique",
        leadership: false,
        firstReference: false,
        secondReference: false,
        sectors: {
            receptionC: false,
            receptionG: false,
            medicalSupport: false,
            observation: true,
            fastCLM: false,
            fastMedication: true,
            concierge: false,
        },
    },
    {
        id: 8,
        name: "Luana",
        leadership: false,
        firstReference: false,
        secondReference: false,
        sectors: {
            receptionC: true,
            receptionG: true,
            medicalSupport: false,
            observation: false,
            fastCLM: false,
            fastMedication: true,
            concierge: false,
        },
    },
    {
        id: 9,
        name: "Lucas",
        leadership: false,
        firstReference: false,
        secondReference: false,
        sectors: {
            receptionC: true,
            receptionG: true,
            medicalSupport: false,
            observation: false,
            fastCLM: false,
            fastMedication: false,
            concierge: false,
        },
    },
    {
        id: 10,
        name: "Magnolia",
        leadership: false,
        firstReference: false,
        secondReference: false,
        sectors: {
            receptionC: true,
            receptionG: true,
            medicalSupport: false,
            observation: false,
            fastCLM: false,
            fastMedication: false,
            concierge: false,
        },
    },
    {
        id: 11,
        name: "Marcus",
        leadership: false,
        firstReference: false,
        secondReference: false,
        sectors: {
            receptionC: false,
            receptionG: false,
            medicalSupport: true,
            observation: false,
            fastCLM: true,
            fastMedication: false,
            concierge: true,
        },
    },
    {
        id: 12,
        name: "Maria",
        leadership: false,
        firstReference: false,
        secondReference: false,
        sectors: {
            receptionC: false,
            receptionG: false,
            medicalSupport: true,
            observation: false,
            fastCLM: true,
            fastMedication: false,
            concierge: true,
        },
    },
    {
        id: 13,
        name: "Naara",
        leadership: false,
        firstReference: false,
        secondReference: false,
        sectors: {
            receptionC: true,
            receptionG: true,
            medicalSupport: false,
            observation: false,
            fastCLM: false,
            fastMedication: true,
            concierge: false,
        },
    },
    {
        id: 14,
        name: "Noemi",
        leadership: false,
        firstReference: false,
        secondReference: false,
        sectors: {
            receptionC: false,
            receptionG: true,
            medicalSupport: false,
            observation: false,
            fastCLM: false,
            fastMedication: true,
            concierge: false,
        },
    },
    {
        id: 15,
        name: "Rayssa",
        leadership: false,
        firstReference: false,
        secondReference: false,
        sectors: {
            receptionC: true,
            receptionG: true,
            medicalSupport: false,
            observation: true,
            fastCLM: false,
            fastMedication: true,
            concierge: false,
        },
    },
    {
        id: 16,
        name: "Sheila",
        leadership: false,
        firstReference: false,
        secondReference: false,
        sectors: {
            receptionC: true,
            receptionG: true,
            medicalSupport: false,
            observation: true,
            fastCLM: false,
            fastMedication: true,
            concierge: false,
        },
    },
    {
        id: 17,
        name: "Taiane",
        leadership: false,
        firstReference: false,
        secondReference: true,
        sectors: {
            receptionC: true,
            receptionG: true,
            medicalSupport: false,
            observation: false,
            fastCLM: false,
            fastMedication: true,
            concierge: false,
        },
    },
    {
        id: 18,
        name: "Thatianny",
        leadership: false,
        firstReference: true,
        secondReference: false,
        sectors: {
            receptionC: false,
            receptionG: false,
            medicalSupport: true,
            observation: false,
            fastCLM: false,
            fastMedication: false,
            concierge: true,
        },
    },
    {
        id: 19,
        name: "Elis",
        leadership: false,
        firstReference: false,
        secondReference: false,
        sectors: {
            receptionC: false,
            receptionG: true,
            medicalSupport: false,
            observation: false,
            fastCLM: false,
            fastMedication: false,
            concierge: false,
        },
    },
];
